name: Build Release Binaries

on:
  workflow_dispatch:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            suffix: linux-x86_64
          - os: macos-latest
            suffix: macos-arm64
          - os: macos-13
            suffix: macos-x86_64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl git

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install curl git

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Hoon compiler
        run: make install-hoonc

      - name: Lint Rust code
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings

      - name: Build Nockchain and wallet
        run: make build

      - name: Package binaries
        run: |
          mkdir -p artifacts
          cp target/release/nockchain artifacts/nockchain-${{ matrix.suffix }}
          cp target/release/nockchain-wallet artifacts/nockchain-wallet-${{ matrix.suffix }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nockchain-binaries-${{ matrix.suffix }}
          path: artifacts/

      - name: (Optional) Download artifacts in another job
        uses: actions/download-artifact@v4
        with:
          name: nockchain-binaries-${{ matrix.suffix }}
          path: artifacts-consumed/
